name: student_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get:
  connectivity_plus: ^6.0.1
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  dots_indicator: ^3.0.0
  flutter_svg: ^2.0.7
  pin_code_fields: ^8.0.1
  flutter_svg_provider: ^1.0.6
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  sms_autofill: ^2.3.0
  grouped_list: ^5.1.2
  intl: ^0.18.1
  percent_indicator: ^4.2.3
  syncfusion_flutter_charts: ^25.1.38
  pinput: ^4.0.0
#  timeline_list: ^0.0.6
  flutter_calendar_carousel: ^2.4.2
  timeline_tile: ^2.0.0
  table_calendar: ^3.0.9
  syncfusion_flutter_datepicker: ^25.1.38
#  flutter_event_calendar: ^1.0.0
#  flutter_neat_and_clean_calendar: ^0.3.14+32

#  carousel_slider: ^4.2.1
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: SF Pro Display
      fonts: 
        - asset: assets/fonts/SFProDisplayBold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplayRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplaySemibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplayMedium.ttf
          weight: 500
    - family: Nunito Sans
      fonts: 
        - asset: assets/fonts/NunitoSansRegular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSansBold.ttf
          weight: 700
    - family: Open Sans
      fonts: 
        - asset: assets/fonts/OpenSansSemiBold.ttf
          weight: 600
