import '../onboarding_two_screen/widgets/activitytracker_item_widget.dart';import 'controller/onboarding_two_controller.dart';import 'models/activitytracker_item_model.dart';import 'package:carousel_slider/carousel_slider.dart';import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;import 'package:smooth_page_indicator/smooth_page_indicator.dart';import 'package:student_app/core/app_export.dart';import 'package:student_app/widgets/app_bar/appbar_image.dart';import 'package:student_app/widgets/app_bar/appbar_image_1.dart';import 'package:student_app/widgets/app_bar/appbar_subtitle_2.dart';import 'package:student_app/widgets/app_bar/custom_app_bar.dart';import 'package:student_app/widgets/custom_elevated_button.dart';class OnboardingTwoScreen extends GetWidget<OnboardingTwoController> {const OnboardingTwoScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: CustomAppBar(height: 100.v, title: AppbarImage(svgPath: ImageConstant.imgGroup, margin: EdgeInsets.only(left: 40.h)), actions: [Padding(padding: EdgeInsets.only(left: 20.h, right: 20.h, bottom: 19.v), child: Column(children: [AppbarSubtitle2(text: "lbl_skip".tr, margin: EdgeInsets.only(left: 71.h), onTap: () {onTapSkip();}), AppbarImage1(svgPath: ImageConstant.imgClock, margin: EdgeInsets.only(top: 10.v, right: 51.h))]))]), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 43.h, vertical: 40.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.end, children: [Spacer(), Container(width: 273.h, margin: EdgeInsets.only(left: 15.h, right: 52.h), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup249), fit: BoxFit.cover)), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(svgPath: ImageConstant.imgMinimize, height: 20.v, width: 46.h, margin: EdgeInsets.only(top: 4.v, bottom: 58.v)), CustomImageView(svgPath: ImageConstant.imgComputer, height: 83.v, width: 72.h)])), SizedBox(height: 93.v), Obx(() => CarouselSlider.builder(options: CarouselOptions(height: 143.v, initialPage: 0, autoPlay: true, viewportFraction: 1.0, enableInfiniteScroll: false, scrollDirection: Axis.horizontal, onPageChanged: (index, reason) {controller.sliderIndex.value = index;}), itemCount: controller.onboardingTwoModelObj.value.activitytrackerItemList.value.length, itemBuilder: (context, index, realIndex) {ActivitytrackerItemModel model = controller.onboardingTwoModelObj.value.activitytrackerItemList.value[index]; return ActivitytrackerItemWidget(model);})), SizedBox(height: 40.v), Align(alignment: Alignment.center, child: Obx(() => SizedBox(height: 8.v, child: AnimatedSmoothIndicator(activeIndex: controller.sliderIndex.value, count: controller.onboardingTwoModelObj.value.activitytrackerItemList.value.length, axisDirection: Axis.horizontal, effect: ScrollingDotsEffect(spacing: 6, activeDotColor: theme.colorScheme.primary, dotColor: theme.colorScheme.primary.withOpacity(0.44), dotHeight: 8.v, dotWidth: 8.h)))))])), bottomNavigationBar: CustomElevatedButton(text: "lbl_next".tr, margin: EdgeInsets.only(left: 20.h, right: 20.h, bottom: 52.v), onTap: () {onTapNext();}))); } 
/// Navigates to the onboardingThreeScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the onboardingThreeScreen.
onTapSkip() { Get.toNamed(AppRoutes.onboardingThreeScreen, ); } 
/// Navigates to the onboardingThreeScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the onboardingThreeScreen.
onTapNext() { Get.toNamed(AppRoutes.onboardingThreeScreen, ); } 
 }
