import '../onboarding_three_screen/widgets/chatwithanystud_item_widget.dart';import 'controller/onboarding_three_controller.dart';import 'models/chatwithanystud_item_model.dart';import 'package:carousel_slider/carousel_slider.dart';import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;import 'package:smooth_page_indicator/smooth_page_indicator.dart';import 'package:student_app/core/app_export.dart';import 'package:student_app/widgets/custom_elevated_button.dart';class OnboardingThreeScreen extends GetWidget<OnboardingThreeController> {const OnboardingThreeScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 51.h, vertical: 68.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup3), fit: BoxFit.cover)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(svgPath: ImageConstant.imgFolder, height: 57.v, width: 56.h, margin: EdgeInsets.only(left: 7.h, top: 9.v)), SizedBox(height: 258.v), CustomImageView(svgPath: ImageConstant.imgDashboard, height: 54.adaptSize, width: 54.adaptSize, alignment: Alignment.centerRight)])), Padding(padding: EdgeInsets.only(left: 43.h, top: 24.v, right: 43.h), child: Obx(() => CarouselSlider.builder(options: CarouselOptions(height: 143.v, initialPage: 0, autoPlay: true, viewportFraction: 1.0, enableInfiniteScroll: false, scrollDirection: Axis.horizontal, onPageChanged: (index, reason) {controller.sliderIndex.value = index;}), itemCount: controller.onboardingThreeModelObj.value.chatwithanystudItemList.value.length, itemBuilder: (context, index, realIndex) {ChatwithanystudItemModel model = controller.onboardingThreeModelObj.value.chatwithanystudItemList.value[index]; return ChatwithanystudItemWidget(model);}))), SizedBox(height: 40.v), Obx(() => SizedBox(height: 8.v, child: AnimatedSmoothIndicator(activeIndex: controller.sliderIndex.value, count: controller.onboardingThreeModelObj.value.chatwithanystudItemList.value.length, axisDirection: Axis.horizontal, effect: ScrollingDotsEffect(spacing: 6, activeDotColor: theme.colorScheme.primary, dotColor: theme.colorScheme.primary.withOpacity(0.44), dotHeight: 8.v, dotWidth: 8.h)))), SizedBox(height: 5.v)])), bottomNavigationBar: CustomElevatedButton(text: "lbl_get_started".tr, margin: EdgeInsets.only(left: 20.h, right: 20.h, bottom: 52.v), onTap: () {onTapGetstarted();}))); } 
/// Navigates to the loginScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the loginScreen.
onTapGetstarted() { Get.toNamed(AppRoutes.loginScreen, ); } 
 }
